### PR TITLE
Added testing framework

### PR DESCRIPTION
**Pull request by bk1713**
I noticed that we have 4 different files instead of a single server.py file. Please note that in my test framework I have just the one server.py file. Kindly keep this point in mind while merging.

### CODE REVIEW

**Review by sfloam — COMMENTED** [review]
Where did JenkinsFile and models.py come from? These are separate issues.

**Review by cfnyu — COMMENTED** [review]
So a couple of things, because my understanding of this User Store is that it was only to setup the testing framework on all of our environments I have the following suggestions: 

1. Remove the Jenkins file. We haven't started talking about Jenkins in class yet so I don't believe this should be in our commits.

2. Remove the models.py and server.py files. There are separate issues created to make these files so I don't think it should be part of this commit.

3. Updates to the requirements files. My suggestion would be to remove the following from the file:
     a.  `pylint` (If we play to add code styling restrictions in the future we can make that an enhancement on a different branch)
     b. both Rspec lines (noseOfYeti and expects) - we will not be using this in our service.

4. Modifications to the `setup.cfg` file. Remove the comments at the bottom as I'm not sure how they apply to our service and remove lines 9 and 10 (references to noy) we won't be using that in our service.

5. Remove test_server_spec.py, test_products.py, and test_server.py. All of these will eventually need to be written as part of other User Stories and so it doesn't make sense to include them here, in my opinion.

As I mentioned, my understanding of the User Story was just to add the framework so we can all begin creating unit test for our code submissions. I think using the professors project as a base and a quick and easy way to test that the framework works is great but I don't think any additional code should be part of this request.

**Comment by Harivadhana** [comment]
I pretty much have the same comments as Christian.

One more thing is that we are adding recommendations and not product. Name of class product (as per naming convention) must be recommendation in the model.py file.

_Suggestion:_ Initially, we can probably have our data as Map<product, List<related_products>> instead of just List<products>.

**Review by Harivadhana — CHANGES_REQUESTED** [review]
I pretty much have the same comments as Christian.
One more thing is that we are adding recommendations and not product. Name of class product (as per naming convention) must be recommendation in the model.py file.

**Comment by Harivadhana** [comment]
_Suggestion:_ Initially, we can probably have our data as Map<product, List<related_products>> instead of just List.

**Comment by sfloam** [comment]
@Harivadhana I'm working on that right now in Create.

**Review by sfloam — COMMENTED** [review]
You should also remove the .DS_Store.
@cfnyu maybe we should add this to gitignore?

**Comment by cfnyu** [comment]
@sfloam it’s already in the gitignore but because his branch was pushed before I made my commit it’s still up here. After all the changes are made to this branch and it’s resubmitted, that file should no longer be tracked by git.

**Pull request merged**
