### PR TITLE
Update Models

### PR DESCRIPTION
**Pull request by Harivadhana**
Merged Recommendation and RecommendationDetails table
BUG: Record not committing to DB. ID is none.

### CODE REVIEW

**Comment by sfloam** [comment]
BUG: Record not committing to DB. ID is none.

Does this mean that this bug is resolved? @Harivadhana

**Comment by sfloam** [comment]
Ran nosetests. Perfect.
Ran server.py and went through the UI. Awesome job.
Created various post requests using PostMan. SOLID JOB!

Good to go!

**Review by sfloam — APPROVED** [review]
See comment below! Tested it out. LOOKS GREAT!

**Review by cfnyu — APPROVED** [review]
All test pass

**Pull request merged**
